services:
  v2board:
    image: vkarz/v2board:fpm-alpine-1.7.4
    container_name: v2board
    restart: unless-stopped
    volumes:
      - ~/nginx/php/html/v2board:/var/www/html/v2board
    depends_on:
      - redis
      - mysql

  redis:
    image: redis:7.2.4
    container_name: redis
    restart: unless-stopped
    command: redis-server /etc/redis/redis.conf
    volumes:
      - ~/redis/data:/data
      - ~/redis/redis.conf:/etc/redis/redis.conf

  mysql:
    image: mysql:8.3.0
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=dimsolo123.
    volumes:
      - ~/mysql/conf:/etc/mysql/conf.d
      - ~/mysql/data:/var/lib/mysql

  acme.sh:
    image: neilpang/acme.sh
    container_name: acme.sh
    command: daemon
    volumes:
      - ~/acmeout:/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DEPLOY_DOCKER_CONTAINER_LABEL=sh.acme.autoload.domain=demo.com
      - DEPLOY_DOCKER_CONTAINER_KEY_FILE=/etc/nginx/ssl/demo.com/key.pem
      - DEPLOY_DOCKER_CONTAINER_CERT_FILE="/etc/nginx/ssl/demo.com/cert.pem"
      - DEPLOY_DOCKER_CONTAINER_CA_FILE="/etc/nginx/ssl/demo.com/ca.pem"
      - DEPLOY_DOCKER_CONTAINER_FULLCHAIN_FILE="/etc/nginx/ssl/demo.com/full.pem"
      - DEPLOY_DOCKER_CONTAINER_RELOAD_CMD="service nginx force-reload"
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ~/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ~/nginx/vhost:/etc/nginx/conf.d
      - ~/nginx/ssl:/etc/nginx/ssl
      - ~/nginx/html:/usr/share/nginx/html
      - ~/nginx/php:/var/www
    labels:
      - sh.acme.autoload.domain=demo.com
