name: v2board caddy fpm Docker Image CI

on:
  workflow_dispatch:
    inputs:
      tags:
        descrption: 'input the docker tag'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download v2board
      run: |
        git clone https://github.com/wyx2685/v2board.git ./nv2board
        cp -ar ./docker/caddy-fpm/. ./nv2board/
        sed -i "s/REDIS_HOST=127.0.0.1/REDIS_HOST=redis/" ./nv2board/.env.example
        sed -i "s/REDIS_PASSWORD=null/REDIS_PASSWORD=redis123./" ./nv2board/.env.example

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./nv2board
        platforms: linux/amd64
        push: true
        file: ./nv2board/Dockerfile
        tags: vkarz/v2board:caddy-fpm-${{ github.event.inputs.tags }},vkarz/v2board:caddy-fpm-latest
