name: v2board fpm Docker Image CI

on:
  workflow_dispatch:
    inputs:
      tags:
        descrption: 'input the docker tag'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download v2board
      run: |
        curl -LJO https://github.com/v2board/v2board/archive/refs/tags/1.7.4.zip
        unzip v2board-1.7.4.zip
        pwd
        mv v2board-1.7.4/* ./docker/fpm/*
        sed -i "s/REDIS_HOST=127.0.0.1/REDIS_HOST=redis/" ./docker/fpm/.env.example
        sed -i "s/REDIS_PASSWORD=null/REDIS_PASSWORD=redis123./" ./docker/fpm/.env.example

    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v3

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v3

    # - name: Login to DockerHub
    #   uses: docker/login-action@v3
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Build and push
    #   uses: docker/build-push-action@v5
    #   with:
    #     context: ./docker/fpm
    #     platforms: linux/amd64
    #     push: true
    #     file: ./docker/fpm/Dockerfile
    #     tags: vkarz/v2board:${{ github.event.inputs.tags }}