name: v2board fpm Docker Image CI

on:
  workflow_dispatch:
    inputs:
      tags:
        descrption: 'input the docker tag'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download v2board
      run: |
        curl -LJO https://github.com/v2board/v2board/archive/refs/tags/1.7.4.zip
        unzip v2board-1.7.4.zip
        pwd
        ls -l