name: XrayR Docker Image CI

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'input the docker tag'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: wyx2685/XrayR

    - name: Add Configuration Files
      run: |
        sed -i "17a COPY ./release/config/config.yml.example /etc/XrayR/config.yml" ./Dockerfile
        sed -i "18a COPY ./release/config/custom_inbound.json /etc/XrayR/custom_inbound.json" ./Dockerfile
        sed -i "19a COPY ./release/config/custom_outbound.json /etc/XrayR/custom_outbound.json" ./Dockerfile
        sed -i "20a COPY ./release/config/dns.json /etc/XrayR/dns.json" ./Dockerfile
        sed -i "21a COPY ./release/config/route.json /etc/XrayR/route.json" ./Dockerfile
        sed -i "22a COPY ./release/config/rulelist /etc/XrayR/rulelist" ./Dockerfile

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        file: ./Dockerfile
        tags: vkarz/xrayr:${{ github.event.inputs.tags }},vkarz/xrayr:latest
