name: XrayR Docker Image CI

on:
  workflow_dispatch:
    inputs:
      tags:
        descrption: 'input the docker tag'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: wyx2685/XrayR

    - name: Add Configuration Files
      run: |
        sed "15a COPY ./release/config/ /etc/XrayR/" ./Dockerfile

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64
        push: true
        file: ./Dockerfile
        tags: vkarz/xrayr:${{ github.event.inputs.tags }}